Repository sungguenja/effective-typescript-study, pull requests merged in 2023-03, with the labels that each got.

#25 Feature/sung/item36 40
  근제/아이템 36 해당 분야의 용어로 타입 이름 짓기.md
  근제/아이템 37 공식 명칭에는 상표를 붙이기.md
  근제/아이템 38 any 타입은 가능한 한 좁은 범위에서만 사용하기.md
  근제/아이템 39 any를 구체적으로 변형해서 사용하기.md
  근제/아이템 40 함수 안으로 타입 단언문 감추기.md
Labels: documentation, 근제

#26 docs: item36-40
  지윤/chapter4/item36.md
  지윤/chapter4/item37.md
  지윤/chapter5/item38.md
  지윤/chapter5/item39.md
  지윤/chapter5/item40.md
Labels: documentation, 지윤

#28 docs: item 41~45
  지윤/chapter5/item41.md
  지윤/chapter5/item42.md
  지윤/chapter5/item43.md
  지윤/chapter5/item44.md
  지윤/chapter6/item45.md
Labels: documentation, 지윤

#30 feat: item 41~45 summarize
  근제/아이템 41 any의 진화를 이해하기.md
  근제/아이템 42 모르는 타입의 값에는 any대신 unknown을 사용하기.md
  근제/아이템 43 몽키 패치보다는 안전한 타입을 사용하기.md
  근제/아이템 44 타입 커버리지를 추적하여 타입 안전성 유지하기.md
  근제/아이템 45 devDependencies에 typescript와 @types추가하기.md
Labels: documentation, 근제

#29 Add: Item 41 - 45 정리
  장후/ch05-any/item-41.md
  장후/ch05-any/item-42.md
  장후/ch05-any/item-43.md
  장후/ch05-any/item-44.md
  장후/ch06-declarations/item-45.md
Labels: documentation, 장후

#33 Feature/sung/item46 52
  근제/아이템 46 타입 선언과 관련된 세 가지 버전 이해하기.md
  근제/아이템 47 공개 API에 등장하는 모든 타입을 익스포트하기.md
  근제/아이템 48 API 주석에 TSDoc 사용하기.md
  근제/아이템 49 콜백에서 this에 대한 타입 제공하기.md
  근제/아이템 50 오버로딩 타입보다는 조건부 타입을 사용하기.md
  근제/아이템 51 의존성 분리를 위해 미러 타입 사용하기.md
  근제/아이템 52 테스팅 타입의 함정에 주의하기.md
Labels: documentation, 근제
