Repository sungguenja/effective-typescript-study, pull requests merged in 2023-01, with the labels that each got.

#1 각자 정리할 폴더 생성 및 pr 템플릿 생성
  .github/pull_request_template.md
  근제/.gitkeep
  장후/.gitkeep
  지윤/.gitkeep
Labels: 근제

#2 아이템 6 정리
  근제/.gitkeep
  근제/아이템 6 편집기를 사용하여 타입 시스템 탐색하기.md
Labels: 근제

#3 아이템 7,8 정리
  근제/아이템 7 타입이 값들의 집합이라고 생각하기.md
  근제/아이템 8 타입 공간과 값 공간의 심벌 구분하기.md
Labels: 근제

#5 아이템9, 아이템10 정리
  근제/아이템 9 타입 단언보다는 타입 선언을 사용하기.md
  근제/아이텝 10 객체 래퍼 타입 피하기.md
Labels: documentation, 근제

#4 docs: 2장 타입스크립트의 타입 시스템
  .github/pull_request_template.md
  지윤/.gitignore
  지윤/.gitkeep
  지윤/chapter2/item10.md
  지윤/chapter2/item6.md
  지윤/chapter2/item7.md
  지윤/chapter2/item8.md
  지윤/chapter2/item9.md
Labels: documentation, 지윤

#6 Docs: From item-6 to item-10
  kimjanghu/ch02-types/item-06.md
  kimjanghu/ch02-types/item-07.md
  kimjanghu/ch02-types/item-08.md
  kimjanghu/ch02-types/item-09.md
  kimjanghu/ch02-types/item-10.md
  kimjanghu/ch02-types/item-12.md
Labels: documentation, 장후

#9 docs: item11~item15
  지윤/chapter2/item11.md
  지윤/chapter2/item12.md
  지윤/chapter2/item13.md
  지윤/chapter2/item14.md
  지윤/chapter2/item15.md
Labels: documentation, 지윤

#7 아이템 11 정리
  근제/아이템 11 잉여 속성 체크의 한계 인지하기.md
Labels: documentation, 근제

#8 아이템 12 정리
  근제/아이템 10 객체 래퍼 타입 피하기.md
  근제/아이템 12 함수 표현식에 타입 적용하기.md
Labels: documentation, 근제

#11 아이템 13-15 정리
  근제/아이템 13 타입과 인터페이스의 차이점 알기.md
  근제/아이템 14 타입 연산과 제너릭 사용으로 반복 줄이기.md
  근제/아이템 15 동적 데이터에 인덱스 시그니처 사용하기.md
Labels: documentation, 근제

#12 chore: move file
  장후/ch02-types/item-06.md
  장후/ch02-types/item-07.md
  장후/ch02-types/item-08.md
  장후/ch02-types/item-09.md
  장후/ch02-types/item-10.md
  장후/ch02-types/item-11.md
  장후/ch02-types/item-12.md
  장후/ch02-types/item-13.md
  장후/ch02-types/item-14.md
  장후/ch02-types/item-15.md
Labels: documentation, 장후

#13 16~20 정리
  근제/아이템 16 number 인덱스 시그니처보다는 Array, 튜플, ArrayLike를 사용하기.md
  근제/아이템 17 변경 관련된 오류 방지를 위해 readonly 사용하기.md
  근제/아이템 18 매핑된 타입을 사용하여 값을 동기화하기.md
  근제/아이템 19 추론 가능한 타입을 사용해 장황한 코드 방지하기.md
  근제/아이템 20 다른 타입에는 다른 변수 사용하기.md
Labels: documentation, 근제

#14 Item 16 ~ 20 정리
  장후/ch02-types/item-16.md
  장후/ch02-types/item-17.md
  장후/ch02-types/item-18.md
  장후/ch03-inference/item-19.md
  장후/ch03-inference/item-20.md
Labels: documentation, 장후
