Repository sungguenja/effective-typescript-study, pull requests merged in 2023-02, with the labels that each got.

#15 docs: item 16-20
  지윤/chapter2/item16.md
  지윤/chapter2/item17.md
  지윤/chapter2/item18.md
  지윤/chapter3/item19.md
  지윤/chapter3/item20.md
Labels: documentation, 지윤

#16 item 21 ~ 25 정리
  근제/아이템 21 타입 넓히기.md
  근제/아이템 22 타입 좁히기.md
  근제/아이템 23 한꺼번에 객체 생성하기.md
  근제/아이템 24 일관성 있는 별칭 사용하기.md
  근제/아이템 25 비동기 코드에는 콜백 대신 async 함수 사용하기.md
Labels: documentation, 근제

#17 item 21 ~ 25 정리
  장후/ch03-inference/item-21.md
  장후/ch03-inference/item-22.md
  장후/ch03-inference/item-23.md
  장후/ch03-inference/item-24.md
  장후/ch03-inference/item-25.md
Labels: documentation, 장후

#18 docs: item21 ~ item25
  지윤/chapter3/item21.md
  지윤/chapter3/item22.md
  지윤/chapter3/item23.md
  지윤/chapter3/item24.md
  지윤/chapter3/item25.md
Labels: documentation, 지윤

#19 아이템 26~30 요약
  근제/아이템 26 타입 추론에 문맥이 어떻게 사용되는지 이해하기.md
  근제/아이템 27 함수형 기법과 라이브러리로 타입 흐름 유지하기.md
  근제/아이템 28 유효한 상태만 표현하는 타입을 지향하기.md
  근제/아이템 29 사용할 때는 너그럽게, 생성할 때는 엄격하게.md
  근제/아이템 30 문서에 타입 정보를 쓰지 않기.md
Labels: documentation, 근제

#20 Add: item 26 - 30 정리
  장후/ch-04-Design/item-28.md
  장후/ch-04-Design/item-29.md
  장후/ch-04-Design/item-30.md
  장후/ch03-inference/item-26.md
  장후/ch03-inference/item-27.md
Labels: documentation, 장후

#24 docs: item31-35
  지윤/chapter4/item31.md
  지윤/chapter4/item32.md
  지윤/chapter4/item33.md
  지윤/chapter4/item34.md
  지윤/chapter4/item35.md
Labels: documentation, 지윤

#23 Add: item 31 - 35 정리
  장후/ch-04-Design/item-31.md
  장후/ch-04-Design/item-32.md
  장후/ch-04-Design/item-33.md
  장후/ch-04-Design/item-34.md
  장후/ch-04-Design/item-35.md
Labels: documentation, 장후

#22 아이템 31 ~ 35 정리
  근제/아이템 31 타입 주변에 null 값 배치하기.md
  근제/아이템 32 유니온의 인터페이스보다는 인터페이스의 유니온을 사용하기.md
  근제/아이템 33 string 타입보다 더 구체적인 타입 사용하기.md
  근제/아이템 34 부정확한 타입보다는 미완성 타입을 사용하기.md
  근제/아이템 35 데이터가 아닌, API와 명세를 보고 타입 만들기.md
Labels: documentation, 근제
